dist: trusty
language: node_js
node_js:
- 10.7
cache:
  yarn: true
  directories:
  - ".npm"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
- export PATH="$HOME/.yarn/bin:$PATH"
- curl https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py | python
install:
- yarn install --ignore-engines
- pipenv install
script:
- yarn test
after_success:
  - pip install awscli --upgrade --user
  - chmod a+x deploy.sh
  - ./deploy.sh
