dist: trusty
language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - ".npm"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn tes
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  access_key_id:
    secure: n94HfDJ1oorv4/VNbzMU6KKq/iewWjQjYZHhjR58mAJKbyzbgcYKxrNTM6RXTZYy2rci1+OfEpoJKjaZNgm1dxNadCmXahdLmaQvjGa9jY6iQKM4JJIlQXmHTyxC7fXwrZwzV/F6b2CIvPHHX0waMJTxH5x+nkOl8EWYyP/lvUsPV/HoRIYFq6ubabd7vo+9DYXkdzXpofPrU+x5WXPCkOfz6BXFjFVngIUMUN2os3rmIzmKayQWYWwFy9sIv4OVZ8dlh20wGOlTiNWTNDInj0ia7yCuzF26sDsn70mJDj+3hH2QhuuwV4b19Ds7P/b5sJbvKFT3oybwCw5scwF79amd3Ln1o0DSmomCeEdrE802AFrtlu4zsNHGc1p9C5ctfICNKWb29Qws2NkvhqoPv9PkLsd1KrsAtu9knBBYrhDnrkWnv4cDlznCx8kjJYAMS2Sra86XHFovXnikH44AfV2E9j0TYIX83rTfVYmEqFi2LA31r4ixteyv8ksQt9Kl8NU5GbYU89cUwT5cuTwLSnNEgWkC4tGqTs8nDv5p3CrL9t7yUSuQeWQzRcUDubytH0v3hVAzavMmooklAhfh/YnOLoODKz/lc7NpxznYTrYRNzO5iF7Gdb1vpFmw4D+zN7aqrrnX5ZubkGtZBdfDBNsyzNGiLTmCeu0SAy3xNTs=
  secret_access_key:
    secure: gykksnRjlvo7PWjHf3Jxpo+kAdgNdVeUgrzI86rTPD5GPkX0VWv2YNNLrj+EIFOARKekkaidMl/MZfqmkN2oZyZ+8nQotldda6K5+pm+qaX2jBQHUpCJ4T08xJ+wkxEDAuwWdXdp/xt5GTBLIqW6hxdmZL11mUUKIJvyV9xE3cdu5x7sJsiymst1f9A/1tMBKkLslLKqv17IdLBNQwX+vwByTPrlTVb7iSSgkm8/mYpAxUDdZdHAfxabBOn6DYUq+PnXttTIYlpo8DXAD8O+Zqg4GYgTXWpxSLEFTn7TTRzQtygKn/8bCSRzPba1OveOgeC5VxzhCF92STGWuY9r+YARcvWdF/UUKYQ86j1k/lRHhmuh1azN3IBTldrGViwm+vCcqzCF1agi2D1ZtgFrNyxQ3PfcRH5C+4I0NbuRwva1Or2YiyBsEaIf0XcfldYuV5A2VTA8YDCcwUtKTXdg1YNGLQEsZqovatPZ5wmP1Ko3ylOnQFnMENR1oLlZ1PKyxSrWrWnJ4NedIFSKWX8PdoggfHGFTa8Dhg0x9u/RDbn1v8PQR8CrR94F3X8h/a0me+g2ITSWva8B8JriZvHWVkr4uLgNaEGk3tu4qSmF6sjE/N+gPpnrfiJ2dz6t7XZOahjo14FdtnGcSWiYK5e0on7yUu0SK6KTkAebY6L83SI=
  app: tramradio-development
  env: TramradioDevelopment-env
  bucket_name: elasticbeanstalk-eu-west-1-847878515230
