dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - ".npm"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn test
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  access_key_id:
    secure: BTqOPhc/aboBUFlcO+EGM6LlKaqomRrYJzf+JRiirhid4mgQlJrHZ9hmfyN3sk17orhWzqFFxxGVsgLK/iLPoor6L6r8dtyb5mXveeqz4pOxWjdiMznIPj0QEMB9XexfWxhjkCM+iaD6k044hvSTUbEcvemNu6OJXRdpgMZS30qSvmqe6es33goAnMq0wmaak4N6+PcG7cIwDA0GsqUINXFgrIJ6fnk1sSfnkOHUgdNjC61igWyx4+jSJ5uAPAndBXHl4mo/m6avKnRS0eM6Fg0fST7f+Im6m29e7TMhOQ7Cj8jV2HskdWgc9UBs0jy/Yc40OZ+vsfqL49VyJP7CNMGazgnHPtESv09FAO81pXIy2RmKl1u6xwab+DtoKN1hNBeVGOBc8zGp4hUGMox/UiP3ngTK3AGpspKm8zqfks70HzPj/xEqXCBFpeKggbe4DmQrfSDtzhc7yLPKRlFIMdIgqNkshqC4r09B/bB5CKNY9870ZQsX+GsmlCMs3SvzRz6wbOmJw4/zrPKtlx5fF6iXAW3QBdzZFnREzHQh+tPPZHNA4BLLxDxFi/vKM288L2PepkSEmjqshMx+AhtIY76pYQF2R2m3+WiWHUx+FRj2P+CGiEWXEFUNRjm82au4Rs734lwp7gqhHzUKXRGmYo8LpG9NM2LYzQ+swbBrwl0=
  secret_access_key:
    secure: QdHffKhduM5j2m+dbLHzK3pkioZ4rovwoLjSjfyZIFGnL6AtsEZNlsz7/BYNfcrz1KL0ZcqpzCHCqEwGVq1wEhwNJbz3VIoAiZNHfhQU/DrOC/zzL8FvtJaEfgLqVPFX4SQgjbgIqxbmZUD2c+vQkrZjQS45Gx39zsY1AvAAdH1hNAsZ/Sqv+YYrWaUK0rLD3I5Csc2brjZ3sa0K+SXXJjVHA5I4SxtYBwg1Kpgb4MnRCu4ZtUBnCjcekXUZauwRD3uJpztwDMqo7BWu2mqcCcfRt8XJb3IjJM/jFlDFBQX4j7hpNdBjvaWyFx7/vfNZGrDcuUMlLkGHN2pvtd4RQFMxGsCzGrWMLnhtcP2isnT+OVnb3BZNEZWWgwGgADmQvZ3+XfyW5jv8MBI7uYinZ0JmmkDF9lYxBNl5CYaWFwSDwFX+L24LNeCqgj6w5pFfcJfoZDV+WNO2Xslm0dCcdtZP9LYjVHdaYmYqNeH6lZ/GAF2WonM9dPlTWW9MsHfOqcdm3ICcaymmOcWYBzqApo2bWVAqa7Y20dn30tCSzSwW2XddAFBmX7vB1JW6z9cuGABNSPmLMXsG5ePS75qZa9jMxgFODyXYaauP/4p4/ujzwLKhgDkSjzwD739aP/w4XgybYjDNS0ooRYZ/UdoytP5lyEgzP4p4vORtKc6r4i0=
  app: tramradio-development
  env: TramradioDevelopment-env
  bucket_name: elasticbeanstalk-eu-west-1-847878515230
